export const SET_QUESTIONS = "SET_QUESTIONS";
export const SET_QUESTION_NUMBER = "SET_QUESTION_NUMBER";

export const SET_TAKER_NAME = "SET_TAKER_NAME ";
export const SET_TAKER_ANSWERS = "SET_TAKER_ANSWERS ";
